### ISSUE TITLE
data file missing

### ISSUE THREAD

**Issue by guangyuli-uoe** [zysite/tagger#2]
hi,

i am trying to run the provided code, but it seems that there is no training data, 
FileNotFoundError: [Errno 2] No such file or directory: 'data/chunking/train.txt'

and the same problem occurred in another repo named post
FileNotFoundError: [Errno 2] No such file or directory: 'data/embed.txt'

looking forward to your reply !

**Comment by yzhangcs** [comment]
@guangyuli-uoe Hi, you can find the chunking files [here](https://www.clips.uantwerpen.be/conll2000/chunking/) (sorrrrrry for my late reply).
